name: integration-ci

on: ["push", "pull_request"]

jobs:
  integration-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: install-capsule
        run: |
          wget -c https://github.com/nervosnetwork/capsule/releases/download/v0.2.3/capsule_v0.2.3_x86_64-linux.tar.gz
          tar -zxvf capsule_v0.2.3_x86_64-linux.tar.gz
          cp capsule_v0.2.3_x86_64-linux/capsule ~/.cargo/bin
      - run: make