name: offchain-modules-ci

on:
  push:
    paths:
      - .github/workflows/offchain-modules.yml
      - 'offchain-modules/**'
  pull_request:
    paths:
      - .github/workflows/offchain-modules.yml
      - 'offchain-modules/**'

defaults:
  run:
    working-directory: offchain-modules

jobs:
  eth-contracts-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: offchain-modules/node_modules
          key: offchain-modules-${{ hashFiles('eth-contracts/yarn.lock') }}
          restore-keys: |
            offchain-modules-
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: install dependencies
        run: yarn --frozen-lockfile
      - run: yarn lint
      - run: yarn test
